### ISSUE TITLE
Reverted PRs are still counts in version calculations

### ISSUE THREAD

**Issue by ilyavolodin** [eslint/eslint-release#10]
Latest ESLint release (v2.7.0) was supposed to be marked as v2.6.1, but version was calculated incorrectly due to the reverted `Update` commit. So it looks like this issue hasn't been fully fixed.

**Comment by ilyavolodin** [comment]
Would also be very nice to add some unit tests for version calculations, just to make sure we are doing the right thing. For example, if there is a lingering bug in major version release calculation, we would probably not know about it, since we've only done one major release with this tool (before it was moved out of ESLint).

**Comment by btmills** [comment]
When I implemented it, we decided to check inside the commit body for the hash of the commit that was reverted - most revert commits have a body of "Reverts commit 1234567890abcdef...". My initial implementation used the title from "Reverts 'Update: Add whatever (fixes #1234)'" and tried to match the title, but that was deemed unreliable (reasonably so). The commit in question (134cb1f) had the title but no body, which is why it didn't catch the revert. I don't know of a way to determine automatically what commit a given commit reverts - both methods I described above rely on the format provided by whomever authored the revert, and as far as I know a revert commit is just a normal commit, just one created automatically by the tools.

There are several tests inside eslint-release around this. This was I think a case it just wasn't designed to cover.

**Comment by nzakas** [comment]
@ilyavolodin how did you revert this commit?

**Comment by ilyavolodin** [comment]
I reverted it from Github UI. But I did add a comment inside the body of the commit. I assume that's why it failed.

**Comment by nzakas** [comment]
Looks like the body of the commit is missing on the revert:

https://github.com/eslint/eslint/commit/134cb1f4f7242d47d54033843a8b4db0b48f6c03

**Comment by ilyavolodin** [comment]
Hmm.. That's strange. I added something like "Reverting for patch release" to the body.

**Comment by nzakas** [comment]
I think the lesson here is just not to modify the revert commit message in any way.

**Comment by ilyavolodin** [comment]
Sure the issue be close then?

**Comment by nzakas** [comment]
I think so. @btmills any other thoughts?

**Comment by btmills** [comment]
This issue demonstrates that the existing solution isn't foolproof, but it isn't a case we could improve, so I think we're good to close it.
